### PR TITLE
Added a privacy notice

### PR DESCRIPTION
**Pull request by opensource-assist**

### CODE REVIEW

**Comment by purarue** [comment]
Hey, Thanks!

Bit confused on the wording here:

> or the service they belong to

Do you mean it doesn't say this is the keepassxc-pwned? Because this [currently does](https://github.com/seanbreckenridge/keepassxc-pwned/blob/master/keepassxc_pwned/password.py#L21), in accordance with the [api spec](https://haveibeenpwned.com/API/v3#UserAgent)

If you think that can be changed somehow, I'm open to suggestions

**Comment by opensource-assist** [comment]
@seanbreckenridge

> Hey, Thanks!
> 
> Bit confused on the wording here:
> 
> > or the service they belong to
> 
> Do you mean it doesn't say this is the keepassxc-pwned? Because this [currently does](https://github.com/seanbreckenridge/keepassxc-pwned/blob/master/keepassxc_pwned/password.py#L21), in accordance with the [api spec](https://haveibeenpwned.com/API/v3#UserAgent)
> 
> If you think that can be changed somehow, I'm open to suggestions

No, by the `service they belong to`, I mean where the passwords belong to; e.g. a password belongs to a Facebook or GitHub account with an specific username.

**Comment by opensource-assist** [comment]
I've clarified the statement a little bit.

**Comment by purarue** [comment]
Thats clearer, but I think it still reads a bit strange.

Moreover, the first statement isn't completely accurate.

Only the first 5 characters of the sha1 hash leave the system, this uses [k-anonymity](https://en.wikipedia.org/wiki/K-anonymity) to do that.

I think both sentences could just be shortened to:

```
This tool only transmits the first 5 characters of the `sha1` hash of your passwords. You can read more about that [here](https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/#cloudflareprivacyandkanonymity).
```

**Pull request merged**
